
devices: /home/oasysusa/ENV/bin/python $(pwd)/oasysusa/scripts/devices.py $(pwd)/production.ini
services: /home/oasysusa/ENV/bin/python $(pwd)/oasysusa/scripts/services.py $(pwd)/production.ini
web: /home/oasysusa/ENV/bin/python $(pwd)/run-prod.py -p
