
devices: /home/oasysusa/ENV/bin/run_oasysusa_devices $(pwd)/production.ini &
services: /home/oasysusa/ENV/bin/run_oasysusa_services $(pwd)/production.ini &
web: /home/oasysusa/ENV/bin/python $(pwd)/run-prod.py -p
