"""2013-04-15_23h22m38s

Revision ID: 1bf2b0d0c056
Revises: None
Create Date: 2013-04-15 23:22:38.699250

"""

# revision identifiers, used by Alembic.
revision = '1bf2b0d0c056'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    ### end Alembic commands ###
