"""2013-07-07_02h30m43s

Revision ID: 1dbc22a52ea1
Revises: 53ff0c4bdbf
Create Date: 2013-07-07 02:30:44.427691

"""

# revision identifiers, used by Alembic.
revision = '1dbc22a52ea1'
down_revision = '53ff0c4bdbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('client', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telephone_number', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('payroll_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_cycle_number', sa.Integer(), nullable=True),
    sa.Column('payroll_cycle_year', sa.Integer(), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('direct_deposit_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('payroll_cycle_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_cycle_id'], ['payroll_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('time_sheet_id', sa.Integer(), nullable=True),
    sa.Column('payroll_cycle_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_cycle_id'], ['payroll_cycles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['time_sheet_id'], ['time_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_segments')
    op.drop_table('time_sheets')
    op.drop_table('payroll_cycles')
    op.drop_table('projects')
    ### end Alembic commands ###
