"""2013-10-28_09h05m44s

Revision ID: 296e7b90dbec
Revises: fe60ad0e511
Create Date: 2013-10-28 09:05:45.887470

"""

# revision identifiers, used by Alembic.
revision = '296e7b90dbec'
down_revision = 'fe60ad0e511'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('manager', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('manager_email', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('manager_telephone_number', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'manager_telephone_number')
    op.drop_column('projects', 'manager_email')
    op.drop_column('projects', 'manager')
    ### end Alembic commands ###
