"""2013-04-22_21h43m39s

Revision ID: 4ba3f71c17f9
Revises: 2e4d4aa02f66
Create Date: 2013-04-22 21:43:39.953624

"""

# revision identifiers, used by Alembic.
revision = '4ba3f71c17f9'
down_revision = '2e4d4aa02f66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('employee_id', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('telephone_number', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('address', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'telephone_number')
    op.drop_column('employees', 'employee_id')
    op.drop_column('employees', 'date_of_birth')
    ### end Alembic commands ###
