"""2013-11-04_13h25m29s

Revision ID: 4ba7faa9f320
Revises: 296e7b90dbec
Create Date: 2013-11-04 19:25:30.788000

"""

# revision identifiers, used by Alembic.
revision = '4ba7faa9f320'
down_revision = '296e7b90dbec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_project',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_project')
    ### end Alembic commands ###
