"""2013-04-30_18h09m07s

Revision ID: 53ff0c4bdbf
Revises: 4ba3f71c17f9
Create Date: 2013-04-30 18:09:07.667768

"""

# revision identifiers, used by Alembic.
revision = '53ff0c4bdbf'
down_revision = '4ba3f71c17f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('provider_id', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'provider_id')
    ### end Alembic commands ###
