"""2013-07-19_01h11m01s

Revision ID: fe60ad0e511
Revises: 1dbc22a52ea1
Create Date: 2013-07-19 01:11:02.440161

"""

# revision identifiers, used by Alembic.
revision = 'fe60ad0e511'
down_revision = '1dbc22a52ea1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupname')
    )
    op.create_table('employee_group',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.add_column(u'employees', sa.Column('password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'employees', 'password')
    op.drop_table('employee_group')
    op.drop_table('groups')
    ### end Alembic commands ###
