environment: production  # environment for rails applications
jruby_min_runtimes: 1 # min number of runtimes
jruby_max_runtimes: 1 # max number of runtimes
libs_dir: lib  # directory where libraries packed as jars can be found
classes_dir: classes # directory where other java classes can be found
default_web_xml: config/web.xml # if you are using a custom web.xml
log: debug
http:
  maxThreads: 800
  connectionTimeout: 10000
---
extensions:
  logging:
    logging_system: logback

