source 'https://rubygems.org'

gem 'rails', '3.2.6'

gem 'cells'


# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'activerecord-jdbcpostgresql-adapter'

gem 'jruby-openssl'
gem 'json'

# JVM Dependencies
#gem 'buildr'

# Servers
gem 'mizuno'
gem 'trinidad'
#gem 'thick'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyrhino'

  gem 'uglifier', '>= 1.0.3'
end

gem 'angularjs-rails'
#gem 'ember-rails'
gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# NoSQL
gem 'redis-rails'
gem 'redis-objects', :require => 'redis/objects'
gem 'mongoid'

# Jobs and Monitoring Tools
gem 'resque' # background jobs
gem 'resque-scheduler' # job scheduling
gem 'resque-history'
gem 'genghisapp'
#gem 'redmon' # Not working on jruby!!!!
#gem 'humongous' # Not working properly on jruby!!!!

# Actors
gem 'celluloid'
gem 'dcell'

# To use debugger
# gem 'ruby-debug'
